# This configuration file is used to configure the Spring Cloud Gateway (static configuration)
spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: r1
            uri: http://localhost:8081
            predicates:
              - Path=/customers/**
          - id: r2
            uri: http://localhost:8082
            predicates:
              - Path=/products/**
